# Generated by Django 5.1.4 on 2025-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_remove_myorders_address_remove_myorders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
