# Generated by Django 5.1.4 on 2025-04-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_myorders_address_myorders_city_myorders_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='seller',
            new_name='admin',
        ),
    ]
