# Generated by Django 5.1.4 on 2025-04-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
