# Generated by Django 5.1.4 on 2025-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
