# Generated by Django 5.1.4 on 2025-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_category_subcategory_myproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
    ]
