# Generated by Django 5.1.4 on 2025-04-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_alter_myproduct_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
