# Generated by Django 5.1.4 on 2025-04-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_alter_category_cpic_alter_myproduct_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Myproduct',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
