# Generated by Django 5.1.4 on 2025-04-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_remove_subcategory_category_name_delete_myproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
