# Generated by Django 5.1.4 on 2025-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_myproduct_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('product_picture', models.CharField(max_length=300, null=True)),
                ('pw', models.CharField(max_length=200, null=True)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('passwd', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='static/userpic/')),
                ('address', models.TextField()),
            ],
        ),
    ]
