# Generated by Django 5.1.4 on 2025-04-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_cart_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
